name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
      - run: python -m pip install numpy
      - run: python -m unittest
